=== appcoreopc/dwig/bqp-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "binary quadratic program schema",
  "type": "object",
  "required":["variable_idxs", "variable_domain", "offset", "linear_terms", "quadratic_terms"],
  "properties": {
    "variable_idxs": {
      "type": "array",
      "items": {
        "type": "integer"
      }
    },
    "variable_domain": {
      "type":"string",
      "enum":["spin", "boolean"]
    },
    "offset" : {
      "type": "number"
    },
    "linear_terms": {
      "type": "array",
      "items": {
        "type": "object",
        "required":["idx", "coeff"],
        "properties": {
          "idx" : {
            "type": "integer"
          },
          "coeff":{
             "type": "number"
          }
        }
      }
    },
    "quadratic_terms": {
      "type": "array",
      "items": {
        "type": "object",
        "required":["idx_1", "idx_2", "coeff"],
        "properties": {
          "idx_1" : {
            "type": "integer"
          },
          "idx_2" : {
            "type": "integer"
          },
          "coeff":{
             "type": "number"
          }
        }
      }
    },
    "description":{
      "type": "string"
    },
    "solutions":{
      "type": "array",
      "items": {
        "type": "object",
        "required":["idx", "assignment"],
        "properties": {
          "idx" : {
            "type": "integer"
          },
          "description" : {
            "type": "string"
          },
          "objective_val" : {
            "type": "number"
          },
          "assignment": {
            "type": "array",
            "items": {
              "type": "object",
              "required":["idx", "val"],
              "properties": {
                "idx" : {
                  "type": "integer"
                },
                "val":{
                  "type": "number"
                }
              }
            }
          }
        }
      }
    }
  }
}

=== appcoreopc/dwig/test/data/wscn_i_2.json
{
  "linear_terms": [
    {
      "coeff": 0.44,
      "idx": 8
    },
    {
      "coeff": 0.44,
      "idx": 9
    },
    {
      "coeff": 0.44,
      "idx": 10
    },
    {
      "coeff": 0.44,
      "idx": 11
    },
    {
      "coeff": 0.44,
      "idx": 12
    },
    {
      "coeff": 0.44,
      "idx": 13
    },
    {
      "coeff": 0.44,
      "idx": 14
    },
    {
      "coeff": 0.44,
      "idx": 15
    },
    {
      "coeff": 0.44,
      "idx": 16
    },
    {
      "coeff": 0.44,
      "idx": 17
    },
    {
      "coeff": 0.44,
      "idx": 18
    },
    {
      "coeff": 0.44,
      "idx": 19
    },
    {
      "coeff": 0.44,
      "idx": 20
    },
    {
      "coeff": 0.44,
      "idx": 21
    },
    {
      "coeff": 0.44,
      "idx": 22
    },
    {
      "coeff": 0.44,
      "idx": 23
    },
    {
      "coeff": 0.44,
      "idx": 32
    },
    {
      "coeff": 0.44,
      "idx": 33
    },
    {
      "coeff": 0.44,
      "idx": 34
    },
    {
      "coeff": 0.44,
      "idx": 35
    },
    {
      "coeff": 0.44,
      "idx": 36
    },
    {
      "coeff": 0.44,
      "idx": 37
    },
    {
      "coeff": 0.44,
      "idx": 38
    },
    {
      "coeff": 0.44,
      "idx": 39
    },
    {
      "coeff": 0.44,
      "idx": 40
    },
    {
      "coeff": 0.44,
      "idx": 41
    },
    {
      "coeff": 0.44,
      "idx": 42
    },
    {
      "coeff": 0.44,
      "idx": 43
    },
    {
      "coeff": 0.44,
      "idx": 44
    },
    {
      "coeff": 0.44,
      "idx": 45
    },
    {
      "coeff": 0.44,
      "idx": 46
    },
    {
      "coeff": 0.44,
      "idx": 47
    },
    {
      "coeff": 0.44,
      "idx": 56
    },
    {
      "coeff": 0.44,
      "idx": 57
    },
    {
      "coeff": 0.44,
      "idx": 58
    },
    {
      "coeff": 0.44,
      "idx": 59
    },
    {
      "coeff": 0.44,
      "idx": 60
    },
    {
      "coeff": 0.44,
      "idx": 61
    },
    {
      "coeff": 0.44,
      "idx": 62
    },
    {
      "coeff": 0.44,
      "idx": 63
    },
    {
      "coeff": -1,
      "idx": 80
    },
    {
      "coeff": -1,
      "idx": 81
    },
    {
      "coeff": -1,
      "idx": 82
    },
    {
      "coeff": -1,
      "idx": 83
    },
    {
      "coeff": -1,
      "idx": 84
    },
    {
      "coeff": -1,
      "idx": 85
    },
    {
      "coeff": -1,
      "idx": 86
    },
    {
      "coeff": -1,
      "idx": 87
    },
    {
      "coeff": -1,
      "idx": 88
    },
    {
      "coeff": -1,
      "idx": 89
    },
    {
      "coeff": -1,
      "idx": 90
    },
    {
      "coeff": -1,
      "idx": 91
    },
    {
      "coeff": -1,
      "idx": 92
    },
    {
      "coeff": -1,
      "idx": 93
    },
    {
      "coeff": -1,
      "idx": 94
    },
    {
      "coeff": -1,
      "idx": 95
    },
    {
      "coeff": -1,
      "idx": 96
    },
    {
      "coeff": -1,
      "idx": 97
    },
    {
      "coeff": -1,
      "idx": 98
    },
    {
      "coeff": -1,
      "idx": 99
    },
    {
      "coeff": -1,
      "idx": 100
    },
    {
      "coeff": -1,
      "idx": 101
    },
    {
      "coeff": -1,
      "idx": 102
    },
    {
      "coeff": -1,
      "idx": 103
    },
    {
      "coeff": -1,
      "idx": 104
    },
    {
      "coeff": -1,
      "idx": 105
    },
    {
      "coeff": -1,
      "idx": 106
    },
    {
      "coeff": -1,
      "idx": 107
    },
    {
      "coeff": -1,
      "idx": 108
    },
    {
      "coeff": -1,
      "idx": 109
    },
    {
      "coeff": -1,
      "idx": 110
    },
    {
      "coeff": -1,
      "idx": 111
    },
    {
      "coeff": -1,
      "idx": 112
    },
    {
      "coeff": -1,
      "idx": 113
    },
    {
      "coeff": -1,
      "idx": 114
    },
    {
      "coeff": -1,
      "idx": 115
    },
    {
      "coeff": -1,
      "idx": 116
    },
    {
      "coeff": -1,
      "idx": 117
    },
    {
      "coeff": -1,
      "idx": 118
    },
    {
      "coeff": -1,
      "idx": 119
    },
    {
      "coeff": -1,
      "idx": 120
    },
    {
      "coeff": -1,
      "idx": 121
    },
    {
      "coeff": -1,
      "idx": 122
    },
    {
      "coeff": -1,
      "idx": 123
    },
    {
      "coeff": -1,
      "idx": 124
    },
    {
      "coeff": -1,
      "idx": 125
    },
    {
      "coeff": -1,
      "idx": 126
    },
    {
      "coeff": -1,
      "idx": 127
    },
    {
      "coeff": -1,
      "idx": 128
    },
    {
      "coeff": -1,
      "idx": 129
    },
    {
      "coeff": -1,
      "idx": 130
    },
    {
      "coeff": -1,
      "idx": 131
    },
    {
      "coeff": -1,
      "idx": 132
    },
    {
      "coeff": -1,
      "idx": 133
    },
    {
      "coeff": -1,
      "idx": 134
    },
    {
      "coeff": -1,
      "idx": 135
    },
    {
      "coeff": -1,
      "idx": 152
    },
    {
      "coeff": -1,
      "idx": 153
    },
    {
      "coeff": -1,
      "idx": 154
    },
    {
      "coeff": -1,
      "idx": 155
    },
    {
      "coeff": -1,
      "idx": 156
    },
    {
      "coeff": -1,
      "idx": 157
    },
    {
      "coeff": -1,
      "idx": 158
    },
    {
      "coeff": -1,
      "idx": 159
    },
    {
      "coeff": 0.44,
      "idx": 160
    },
    {
      "coeff": 0.44,
      "idx": 161
    },
    {
      "coeff": 0.44,
      "idx": 162
    },
    {
      "coeff": 0.44,
      "idx": 163
    },
    {
      "coeff": 0.44,
      "idx": 164
    },
    {
      "coeff": 0.44,
      "idx": 165
    },
    {
      "coeff": 0.44,
      "idx": 166
    },
    {
      "coeff": 0.44,
      "idx": 167
    },
    {
      "coeff": 0.44,
      "idx": 168
    },
    {
      "coeff": 0.44,
      "idx": 169
    },
    {
      "coeff": 0.44,
      "idx": 170
    },
    {
      "coeff": 0.44,
      "idx": 171
    },
    {
      "coeff": 0.44,
      "idx": 172
    },
    {
      "coeff": 0.44,
      "idx": 173
    },
    {
      "coeff": 0.44,
      "idx": 174
    },
    {
      "coeff": 0.44,
      "idx": 175
    },
    {
      "coeff": -1,
      "idx": 176
    },
    {
      "coeff": -1,
      "idx": 177
    },
    {
      "coeff": -1,
      "idx": 178
    },
    {
      "coeff": -1,
      "idx": 179
    },
    {
      "coeff": -1,
      "idx": 180
    },
    {
      "coeff": -1,
      "idx": 181
    },
    {
      "coeff": -1,
      "idx": 182
    },
    {
      "coeff": -1,
      "idx": 183
    },
    {
      "coeff": 0.44,
      "idx": 184
    },
    {
      "coeff": 0.44,
      "idx": 185
    },
    {
      "coeff": 0.44,
      "idx": 186
    },
    {
      "coeff": 0.44,
      "idx": 187
    },
    {
      "coeff": 0.44,
      "idx": 188
    },
    {
      "coeff": 0.44,
      "idx": 189
    },
    {
      "coeff": 0.44,
      "idx": 190
    },
    {
      "coeff": 0.44,
      "idx": 191
    },
    {
      "coeff": 0.44,
      "idx": 192
    },
    {
      "coeff": 0.44,
      "idx": 193
    },
    {
      "coeff": 0.44,
      "idx": 194
    },
    {
      "coeff": 0.44,
      "idx": 195
    },
    {
      "coeff": 0.44,
      "idx": 196
    },
    {
      "coeff": 0.44,
      "idx": 197
    },
    {
      "coeff": 0.44,
      "idx": 198
    },
    {
      "coeff": 0.44,
      "idx": 199
    },
    {
      "coeff": -1,
      "idx": 200
    },
    {
      "coeff": -1,
      "idx": 201
    },
    {
      "coeff": -1,
      "idx": 202
    },
    {
      "coeff": -1,
      "idx": 203
    },
    {
      "coeff": -1,
      "idx": 204
    },
    {
      "coeff": -1,
      "idx": 205
    },
    {
      "coeff": -1,
      "idx": 206
    },
    {
      "coeff": -1,
      "idx": 207
    },
    {
      "coeff": 0.44,
      "idx": 208
    },
    {
      "coeff": 0.44,
      "idx": 209
    },
    {
      "coeff": 0.44,
      "idx": 210
    },
    {
      "coeff": 0.44,
      "idx": 211
    },
    {
      "coeff": 0.44,
      "idx": 212
    },
    {
      "coeff": 0.44,
      "idx": 213
    },
    {
      "coeff": 0.44,
      "idx": 214
    },
    {
      "coeff": 0.44,
      "idx": 215
    },
    {
      "coeff": 0.44,
      "idx": 216
    },
    {
      "coeff": 0.44,
      "idx": 217
    },
    {
      "coeff": 0.44,
      "idx": 218
    },
    {
      "coeff": 0.44,
      "idx": 219
    },
    {
      "coeff": 0.44,
      "idx": 220
    },
    {
      "coeff": 0.44,
      "idx": 221
    },
    {
      "coeff": 0.44,
      "idx": 222
    },
    {
      "coeff": 0.44,
      "idx": 223
    },
    {
      "coeff": -1,
      "idx": 224
    },
    {
      "coeff": -1,
      "idx": 225
    },
    {
      "coeff": -1,
      "idx": 226
    },
    {
      "coeff": -1,
      "idx": 227
    },
    {
      "coeff": -1,
      "idx": 228
    },
    {
      "coeff": -1,
      "idx": 229
    },
    {
      "coeff": -1,
      "idx": 230
    },
    {
      "coeff": -1,
      "idx": 231
    },
    {
      "coeff": 0.44,
      "idx": 232
    },
    {
      "coeff": 0.44,
      "idx": 233
    },
    {
      "coeff": 0.44,
      "idx": 234
    },
    {
      "coeff": 0.44,
      "idx": 235
    },
    {
      "coeff": 0.44,
      "idx": 236
    },
    {
      "coeff": 0.44,
      "idx": 237
    },
    {
      "coeff": 0.44,
      "idx": 238
    },
    {
      "coeff": 0.44,
      "idx": 239
    },
    {
      "coeff": 0.44,
      "idx": 240
    },
    {
      "coeff": 0.44,
      "idx": 241
    },
    {
      "coeff": 0.44,
      "idx": 242
    },
    {
      "coeff": 0.44,
      "idx": 243
    },
    {
      "coeff": 0.44,
      "idx": 244
    },
    {
      "coeff": 0.44,
      "idx": 245
    },
    {
      "coeff": 0.44,
      "idx": 246
    },
    {
      "coeff": 0.44,
      "idx": 247
    },
    {
      "coeff": -1,
      "idx": 248
    },
    {
      "coeff": -1,
      "idx": 249
    },
    {
      "coeff": -1,
      "idx": 250
    },
    {
      "coeff": -1,
      "idx": 251
    },
    {
      "coeff": -1,
      "idx": 252
    },
    {
      "coeff": -1,
      "idx": 253
    },
    {
      "coeff": -1,
      "idx": 254
    },
    {
      "coeff": -1,
      "idx": 255
    },
    {
      "coeff": 0.44,
